name: Auto-Follow-Back-Github-Users

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  follow-back:
    runs-on: ubuntu-latest
    steps:
      - name: Run Auto Follow Action
        uses: Huniko519/Github-Auto-Follow-Unfollow-View-User-List@main
        with:
          token: ${{ secrets.GH_FOLLOW_PAT }}
          repository: ${{ github.repository }}
          isEnableFollow: true
          isEnableUnfollow: false
          isReadmeUpdate: false
